//! Fixed-point exponentiation in Q64.64.
//!
//! Two primitives carry the whole price ladder:
//!
//! * [`pow_q64_signed`] — `base^n` for a signed integer `n`, by binary
//!   exponentiation. Used for the taper factor `tau^i`.
//! * [`exp2`] — `2^v` for a signed Q64.64 `v`. Used to turn a log2 price into
//!   a price.
//!
//! Both round *down* at every step. That makes them deterministic, which
//! matters far more than being close to the real-valued answer: these
//! functions do not approximate the ladder, they **define** it.

use crate::constants::ONE_Q64;
use crate::errors::{CoreError, Result};
use crate::require;
use crate::math::u256::{div_q64, mul_q64};

/// `2^(2^-k)` in Q64.64 for `k = 1..=64`, generated by repeated integer
/// square root of 2.0 so the values are reproducible rather than transcribed.
pub const EXP2_TABLE: [u128; 64] = [
    26087635650665564424, // 2^(2^-1)
    21936999301089678046, // 2^(2^-2)
    20116317054877281741, // 2^(2^-3)
    19263451207323153961, // 2^(2^-4)
    18850675170876015534, // 2^(2^-5)
    18647615946650685158, // 2^(2^-6)
    18546908069882975959, // 2^(2^-7)
    18496758270674070880, // 2^(2^-8)
    18471734244850835105, // 2^(2^-9)
    18459234930309000271, // 2^(2^-10)
    18452988445124272032, // 2^(2^-11)
    18449865995240371897, // 2^(2^-12)
    18448304968436414828, // 2^(2^-13)
    18447524504564044945, // 2^(2^-14)
    18447134285009651014, // 2^(2^-15)
    18446939178327825411, // 2^(2^-16)
    18446841625760745901, // 2^(2^-17)
    18446792849670663276, // 2^(2^-18)
    18446768461673986096, // 2^(2^-19)
    18446756267687738521, // 2^(2^-20)
    18446750170697637485, // 2^(2^-21)
    18446747122203342654, // 2^(2^-22)
    18446745597956384161, // 2^(2^-23)
    18446744835832952145, // 2^(2^-24)
    18446744454771247944, // 2^(2^-25)
    18446744264240398796, // 2^(2^-26)
    18446744168974974960, // 2^(2^-27)
    18446744121342263226, // 2^(2^-28)
    18446744097525907405, // 2^(2^-29)
    18446744085617729506, // 2^(2^-30)
    18446744079663640560, // 2^(2^-31)
    18446744076686596087, // 2^(2^-32)
    18446744075198073851, // 2^(2^-33)
    18446744074453812733, // 2^(2^-34)
    18446744074081682174, // 2^(2^-35)
    18446744073895616894, // 2^(2^-36)
    18446744073802584254, // 2^(2^-37)
    18446744073756067934, // 2^(2^-38)
    18446744073732809774, // 2^(2^-39)
    18446744073721180694, // 2^(2^-40)
    18446744073715366154, // 2^(2^-41)
    18446744073712458884, // 2^(2^-42)
    18446744073711005249, // 2^(2^-43)
    18446744073710278432, // 2^(2^-44)
    18446744073709915023, // 2^(2^-45)
    18446744073709733319, // 2^(2^-46)
    18446744073709642467, // 2^(2^-47)
    18446744073709597041, // 2^(2^-48)
    18446744073709574328, // 2^(2^-49)
    18446744073709562971, // 2^(2^-50)
    18446744073709557293, // 2^(2^-51)
    18446744073709554454, // 2^(2^-52)
    18446744073709553034, // 2^(2^-53)
    18446744073709552324, // 2^(2^-54)
    18446744073709551969, // 2^(2^-55)
    18446744073709551792, // 2^(2^-56)
    18446744073709551703, // 2^(2^-57)
    18446744073709551659, // 2^(2^-58)
    18446744073709551637, // 2^(2^-59)
    18446744073709551626, // 2^(2^-60)
    18446744073709551620, // 2^(2^-61)
    18446744073709551617, // 2^(2^-62)
    18446744073709551616, // 2^(2^-63)
    18446744073709551616, // 2^(2^-64)
];

/// Largest integer exponent `exp2` will accept. `2^63` in Q64.64 needs 127
/// bits; one more would not fit.
pub const MAX_EXP2_INT: i128 = 62;
/// Smallest integer exponent `exp2` will accept before the result floors to
/// zero.
pub const MIN_EXP2_INT: i128 = -63;

/// `2^f` for the Q64.64 fraction `f` in `[0, 1)`. Result lies in `[1.0, 2.0)`.
///
/// Each set bit of `f` contributes one table multiply, so a small `f` — the
/// common case for a bin width — costs only a handful of them.
pub fn exp2_frac(frac: u128) -> Result<u128> {
    let mut result = ONE_Q64;
    for (j, factor) in EXP2_TABLE.iter().enumerate() {
        if frac & (1u128 << (63 - j)) != 0 {
            result = mul_q64_unit(result, *factor);
        }
    }
    Ok(result)
}

/// `floor(a * b / 2^64)` for two Q64.64 values that both lie in `[1.0, 2.0)`.
///
/// Writing `a = 1 + ra` and `b = 1 + rb`, the 128x128 product collapses to a
/// single 64x64 one:
///
/// ```text
///   a*b / 2^64  =  1 + ra + rb + (ra * rb) / 2^64
/// ```
///
/// The first three terms are exact integers, so flooring the last one gives
/// bit-for-bit the same answer as the general [`mul_q64`]. `exp2_frac` runs
/// this up to 64 times per call and it is the hottest loop in the program,
/// which is why it is worth not going through `U256` at all.
///
/// Only valid on the unit octave; every caller here is a table entry or a
/// running product of them, and both stay inside it.
#[inline]
fn mul_q64_unit(a: u128, b: u128) -> u128 {
    debug_assert!(a >= ONE_Q64 && a < 2 * ONE_Q64);
    debug_assert!(b >= ONE_Q64 && b < 2 * ONE_Q64);
    let ra = (a - ONE_Q64) as u64 as u128;
    let rb = (b - ONE_Q64) as u64 as u128;
    ONE_Q64 + ra + rb + ((ra * rb) >> 64)
}

/// `2^v` where `v` is a signed Q64.64 log2 value; the result is Q64.64.
///
/// Errors rather than saturating once the result would leave the
/// representable band, which is exactly the signal the ladder uses to find
/// its own bin-id bounds.
pub fn exp2(v: i128) -> Result<u128> {
    let int_part = v >> 64; // arithmetic shift == floor for negatives
    require!(
        (MIN_EXP2_INT..=MAX_EXP2_INT).contains(&int_part),
        CoreError::PriceOutOfRange
    );

    let frac = (v - (int_part << 64)) as u128;
    let base = exp2_frac(frac)?; // [2^64, 2^65)

    let out = if int_part >= 0 {
        base.checked_shl(int_part as u32)
            .filter(|r| (r >> int_part as u32) == base)
            .ok_or(CoreError::PriceOutOfRange)?
    } else {
        base >> (-int_part) as u32
    };

    require!(out > 0, CoreError::PriceOutOfRange);
    Ok(out)
}

/// `ln(2)` in Q64.64.
pub const LN2_Q64: u128 = 12_786_308_645_202_655_659;

/// `2^w - 1` for a small `w`, via the exponential series rather than the
/// table walk.
///
/// Bin widths are at most ~0.057 in log2 (a 400 bps bin), so with
/// `u = w * ln2 <= 0.04` the quartic truncation error is under `u^5/120`,
/// around 1e-11 relative. That is far below the 1e-6 resolution the result is
/// reported at, and unlike [`exp2`] this costs four multiplies instead of
/// thirty-odd — which matters because every bin initialisation calls it.
///
/// Only used for bin *widths*, never for prices: prices must come from the
/// one canonical [`exp2`] so a bin's price is a pure function of its id.
pub fn exp2_minus_one_small(w: u128) -> Result<u128> {
    require!(w < ONE_Q64 / 8, CoreError::MathOverflow);
    let u = mul_q64(w, LN2_Q64)?;
    let u2 = mul_q64(u, u)?;
    let u3 = mul_q64(u2, u)?;
    let u4 = mul_q64(u3, u)?;
    Ok(u + u2 / 2 + u3 / 6 + u4 / 24)
}

/// `base^exp` in Q64.64 by binary exponentiation.
pub fn pow_q64(base: u128, mut exp: u32) -> Result<u128> {
    let mut result = ONE_Q64;
    let mut acc = base;
    while exp > 0 {
        if exp & 1 == 1 {
            result = mul_q64(result, acc)?;
        }
        exp >>= 1;
        if exp > 0 {
            acc = mul_q64(acc, acc)?;
        }
    }
    Ok(result)
}

/// `base^exp` in Q64.64 for a signed exponent. A negative exponent takes the
/// reciprocal, which overflows once `base^|exp|` underflows towards zero —
/// the bound that caps how far below the anchor the ladder can reach.
pub fn pow_q64_signed(base: u128, exp: i32) -> Result<u128> {
    if exp >= 0 {
        pow_q64(base, exp as u32)
    } else {
        let p = pow_q64(base, exp.unsigned_abs())?;
        require!(p > 0, CoreError::PriceOutOfRange);
        div_q64(ONE_Q64, p)
    }
}

#[cfg(test)]
pub(crate) fn q64_to_f64(v: u128) -> f64 {
    (v >> 64) as f64 + ((v & (ONE_Q64 - 1)) as f64) / (ONE_Q64 as f64)
}

#[cfg(test)]
pub(crate) fn f64_to_q64(v: f64) -> u128 {
    (v * (ONE_Q64 as f64)) as u128
}

#[cfg(test)]
pub(crate) mod tests {
    use super::*;

    fn rel_err(got: f64, want: f64) -> f64 {
        if want == 0.0 {
            got.abs()
        } else {
            ((got - want) / want).abs()
        }
    }

    /// Accuracy is bounded by two separate things: the algorithm's own
    /// truncation (`base_tol`), and how much a Q64.64 value can resolve at
    /// this magnitude at all (one ulp is `2^-64` absolute, which is a *huge*
    /// relative error for a small price). Asserting against their sum keeps
    /// the test meaningful across the whole band instead of only near 1.0.
    pub(crate) fn assert_rel(got: f64, want: f64, base_tol: f64, ctx: &str) {
        let ulp_rel = 2f64.powi(-64) / want.abs();
        let tol = base_tol + 4.0 * ulp_rel;
        assert!(
            rel_err(got, want) <= tol,
            "{ctx}: got {got}, want {want}, tol {tol}"
        );
    }

    #[test]
    fn exp2_of_zero_is_one() {
        assert_eq!(exp2(0).unwrap(), ONE_Q64);
    }

    #[test]
    fn exp2_of_whole_numbers_is_an_exact_shift() {
        for n in 0..=62i128 {
            assert_eq!(exp2(n << 64).unwrap(), ONE_Q64 << n, "2^{n}");
        }
        for n in 1..=63i128 {
            assert_eq!(exp2(-(n << 64)).unwrap(), ONE_Q64 >> n, "2^-{n}");
        }
    }

    #[test]
    fn exp2_tracks_f64_in_the_working_band() {
        let samples = [
            -40.0, -32.25, -10.125, -1.5, -0.75, -0.001, 0.0, 0.001, 0.5, 1.5, 10.125, 32.25, 60.5,
        ];
        for v in samples {
            let q = (v * (ONE_Q64 as f64)) as i128;
            let got = q64_to_f64(exp2(q).unwrap());
            let want = 2f64.powf(v);
            assert_rel(got, want, 1e-11, &format!("2^{v}"));
        }
    }

    #[test]
    fn exp2_precision_degrades_near_the_bottom_of_the_band() {
        // A Q64.64 value has only 64 fractional bits, so 2^-60 retains about
        // four significant bits. `exp2` still succeeds there, which is why
        // `Ladder::validate_range` checks that adjacent bins stay distinct
        // rather than trusting representability alone.
        let v = -60.5f64;
        let got = q64_to_f64(exp2((v * (ONE_Q64 as f64)) as i128).unwrap());
        let want = 2f64.powf(v);
        assert!(rel_err(got, want) > 1e-3, "expected coarse output, got {got}");
        assert!(rel_err(got, want) < 0.5);
    }

    #[test]
    fn exp2_is_monotonic_over_fine_steps() {
        // Steps of 2^-30 in the exponent, far finer than any real bin width.
        let step = (ONE_Q64 >> 30) as i128;
        let mut prev = exp2(-step * 500).unwrap();
        for k in -499..=500i128 {
            let cur = exp2(step * k).unwrap();
            assert!(cur > prev, "not monotonic at k={k}");
            prev = cur;
        }
    }

    #[test]
    fn exp2_rejects_out_of_band_exponents() {
        assert!(exp2(63i128 << 64).is_err());
        assert!(exp2(-(64i128 << 64)).is_err());
    }

    #[test]
    fn pow_of_one_is_one() {
        for e in [0u32, 1, 2, 1000, 100_000] {
            assert_eq!(pow_q64(ONE_Q64, e).unwrap(), ONE_Q64);
            assert_eq!(pow_q64_signed(ONE_Q64, e as i32).unwrap(), ONE_Q64);
            assert_eq!(pow_q64_signed(ONE_Q64, -(e as i32)).unwrap(), ONE_Q64);
        }
    }

    #[test]
    fn pow_matches_f64_for_a_realistic_taper() {
        // tau = 0.9999, the shape a live pool would use.
        let tau = f64_to_q64(0.9999);
        for n in [1i32, 10, 100, 1_000, 10_000, 50_000] {
            let got = q64_to_f64(pow_q64_signed(tau, n).unwrap());
            let want = 0.9999f64.powi(n);
            assert!(rel_err(got, want) < 1e-9, "tau^{n}: got {got}, want {want}");

            let got_neg = q64_to_f64(pow_q64_signed(tau, -n).unwrap());
            let want_neg = 0.9999f64.powi(-n);
            assert!(
                rel_err(got_neg, want_neg) < 1e-9,
                "tau^-{n}: got {got_neg}, want {want_neg}"
            );
        }
    }

    #[test]
    fn pow_is_strictly_decreasing_below_one() {
        let tau = f64_to_q64(0.999);
        let mut prev = ONE_Q64;
        for n in 1..200u32 {
            let cur = pow_q64(tau, n).unwrap();
            assert!(cur < prev, "tau^{n} did not decrease");
            prev = cur;
        }
    }

    #[test]
    fn negative_pow_overflows_once_the_base_underflows() {
        // 0.5^-200 is astronomically large and must not silently wrap.
        assert!(pow_q64_signed(ONE_Q64 / 2, -200).is_err());
    }

    #[test]
    fn the_small_width_series_agrees_with_the_full_exp2() {
        // Widths across the whole legal band, from 0.01 bps to 400 bps.
        for bps in [0.01f64, 0.1, 1.0, 10.0, 25.0, 100.0, 400.0] {
            let w = f64_to_q64((1.0 + bps / 10_000.0).log2());
            let fast = exp2_minus_one_small(w).unwrap();
            let exact = exp2(w as i128).unwrap() - ONE_Q64;

            // Worst case is the widest bin, where the quartic truncation
            // leaves ~2e-8 relative. That is 8e-4 of a single step unit at
            // 400 bps, so the two agree on the only thing that is stored.
            let rel = (fast as f64 - exact as f64).abs() / exact as f64;
            assert!(rel < 1e-7, "{bps} bps: fast {fast}, exact {exact}, rel {rel}");

            let units = |v: u128| (q64_to_f64(v) * 1e6).round() as u64;
            assert_eq!(
                units(fast),
                units(exact),
                "{bps} bps: the stored step unit must not depend on which one is used"
            );

            // And it recovers the bin step it was built from.
            assert!(
                (units(fast) as f64 - bps * 100.0).abs() < 0.5,
                "{bps} bps -> {} units",
                units(fast)
            );
        }
    }

    #[test]
    fn the_small_width_series_refuses_inputs_it_was_not_built_for() {
        // The quartic truncation is only accurate for small w.
        assert!(exp2_minus_one_small(ONE_Q64 / 2).is_err());
        assert!(exp2_minus_one_small(ONE_Q64).is_err());
    }

    #[test]
    fn the_unit_octave_multiply_is_identical_to_the_general_one() {
        // Every table entry against every other, plus the running products
        // exp2_frac actually produces. Any divergence here would silently
        // shift the whole price ladder.
        for a in EXP2_TABLE.iter().copied() {
            for b in EXP2_TABLE.iter().copied() {
                assert_eq!(
                    mul_q64_unit(a, b),
                    mul_q64(a, b).unwrap(),
                    "table entries {a} x {b}"
                );
            }
        }
        let mut running = ONE_Q64;
        for factor in EXP2_TABLE.iter().copied() {
            assert_eq!(mul_q64_unit(running, factor), mul_q64(running, factor).unwrap());
            running = mul_q64_unit(running, factor);
            assert!(running >= ONE_Q64 && running < 2 * ONE_Q64);
        }
    }

    #[test]
    fn exp2_frac_stays_in_the_unit_octave() {
        for f in [0u128, 1, ONE_Q64 / 3, ONE_Q64 / 2, ONE_Q64 - 1] {
            let r = exp2_frac(f).unwrap();
            assert!(r >= ONE_Q64 && r < 2 * ONE_Q64, "frac {f} -> {r}");
        }
    }
}
